{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ontology-hub.fullname" . }}-mongodb
  labels:
    {{- include "ontology-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | quote }}
{{- end }}
